export const GEOMETRY = "Geometry"
export const MATERIAL = "Material"
export const DEFAULT_FOV = 75
export const DEFAULT_ASPECT = 1
export const DEFAULT_NEAR = 0.1
export const DEFAULT_FAR = 10000
export const WINDOW_MARGIN_X = 2
export const WINDOW_MARGIN_Y = 2
export const ROW_HEIGHT = window.innerHeight/30
export const CONTAINER_WIDTH= window.innerWidth
export const GRID_COLUMNS = 12
export const NON_DRAGGABLE = "nonDraggable"
export const SPHERE_BUFFER_GEOMETRY = "Sphere"
export const MESH_BASIC_MATERIAL = "Basic"
export const MAIN_SCENE = "main"
export const JPG= "jpg" || "jpeg"
export const HDR= "hdr"