export const CAMERA = "Camera"
export const DEFAULT_FOV = 75
export const DEFAULT_ASPECT = 1
export const DEFAULT_NEAR = 0.1
export const DEFAULT_FAR = 10000
export const WINDOW_MARGIN_X = 5
export const WINDOW_MARGIN_Y = 5
export const ROW_HEIGHT = window.innerHeight/30
export const CONTAINER_WIDTH= window.innerWidth
export const GRID_COLUMNS = 12